import * as vscode from 'vscode';

import { RequirementAnalyzer } from './analyzer/requirementAnalyzer';
import {
    RequirementAnalysis,
    FunctionalRequirement,
    BusinessRule,
    Risk,
    TestScenario
} from './models/requirementAnalysis';

export function activate(context: vscode.ExtensionContext) {

    console.log('QA Copilot Activated');

    const analyzer = new RequirementAnalyzer();

    const disposable = vscode.commands.registerCommand(
        'requirementAnalyzer.analyze',
        async () => {

            const requirement = await vscode.window.showInputBox({
                placeHolder: 'Paste your requirement here...',
                prompt: 'QA Copilot Requirement Analyzer'
            });

            if (!requirement) {
                return;
            }

            try {

                const analysis = await analyzer.analyze(requirement);

                const markdown = buildMarkdown(analysis);

                const document =
                    await vscode.workspace.openTextDocument({
                        content: markdown,
                        language: "markdown"
                    });

                await vscode.window.showTextDocument(document);

            } catch (error) {

                vscode.window.showErrorMessage(
                    error instanceof Error
                        ? error.message
                        : "Unknown error"
                );

            }

        }
    );

    context.subscriptions.push(disposable);

}

function buildMarkdown(
    analysis: RequirementAnalysis
): string {

    return `# 🤖 Requirement Analyzer Report

---

# 📋 Summary

${analysis.summary}

---

# ✅ Functional Requirements

${formatNamedItems(analysis.functionalRequirements)}

---

# 📌 Business Rules

${formatNamedItems(analysis.businessRules)}

---

# ⚠ Risks

${formatNamedItems(analysis.risks)}

---

# 🧪 Test Scenarios

${formatScenarios(analysis.testScenarios)}

---

*Generated by Requirement Analyzer*
`;

}

function formatNamedItems(
    items: FunctionalRequirement[] | BusinessRule[] | Risk[]
): string {

    if (!items.length) {
        return "None";
    }

    return items.map(item =>
`### ${item.name}

${item.description}
`).join("\n");

}

function formatScenarios(
    scenarios: TestScenario[]
): string {

    if (!scenarios.length) {
        return "None";
    }

    return scenarios.map((item, index) =>
`${index + 1}. ${item.scenario}

${item.description}
`).join("\n");

}

export function deactivate() {}